name: Check Release
inputs:
  owner:
    description: "Owner"
    required: true
    example: "esphome"
  repo:
    description: "Repo"
    required: true
    example: "home-assistant-addon"
runs:
  using: "composite"
  steps:
    - name: Get current release
      id: get
      shell: bash
      run: |
        # 获取当前仓库的最新 Release 信息
        response=$(curl -s -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/releases/latest")
        
        # 提取版本号和 URL
        current_version=$(echo "$response" | jq -r '.tag_name')
        release_url=$(echo "$response" | jq -r '.html_url')
        body="[CHANGELOG.md](https://github.com/${{ inputs.owner }}/${{ inputs.repo }}/releases/tag/$current_version)"
#        body=$(echo "$response" | jq -r '.body | @json')
        
        # 使用 GitHub 环境文件格式设置变量
        echo "current_version<<EOF" >> $GITHUB_OUTPUT
        echo "$current_version" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "release_url<<EOF" >> $GITHUB_OUTPUT
        echo "$release_url" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "$body" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # 打印调试信息
        echo "Current release: $current_version"
        echo "Release url: $release_url"
        echo "Body: $body"

    - name: Compare with previous release
      id: compare
      uses: ./.github/actions/compare-with-previous
      with:
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        current_version: ${{ steps.get.outputs.current_version }}
        release_url: ${{ steps.get.outputs.release_url }}
        body: ${{ steps.get.outputs.body }}
